<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MacBook-Air-Tim.local" failures="1" tests="5" name="SampleTests" time="0.011" errors="0" timestamp="2025-01-10T22:06:02 GET">
  <testcase classname="com.testng.listeners.SampleTestClass" name="skippedTest" time="0.0">
    <skipped/>
  </testcase> <!-- skippedTest -->
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.0"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testGetData" time="0.0"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testOne" time="0.0"/>
  <testcase classname="com.testng.listeners.SampleTestClass" name="testThree" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.SampleTestClass.testThree(SampleTestClass.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- SampleTests -->
